var amount = 8;
var sitebytext = new Array(amount);
let random = Math.floor(Math.random() * amount) + 1;
sitebytext[1]="website by <a href='https://rubberocket.com' class='alephdlink'>website by rubberocket.com</a>";
sitebytext[2]="<a href='https://rubberocket.com' class='alephdlink'>aleph was here</a> :)";
sitebytext[3]="<a href='https://rubberocket.com' class='alephdlink'>rubberocket</a> is responsible for the site.";
sitebytext[4]="<a href='https://rubberocket.com' class='alephdlink'>just who created this mess?!</a>.";
sitebytext[5]="<a href='https://rubberocket.com' class='alephdlink'>like what you see? click here</a>.";
sitebytext[6]="undefined";
sitebytext[7]="null";
sitebytext[8]="lull";
document.write(sitebytext[random]);
